baseURL = 'https://hot-potato-archive.pages.dev'
languageCode = 'ko-kr'
defaultContentLanguage = 'ko'
title = "뜨거운 감자 아카이빙: hot potato archive"

ignoreFiles = ["blog-template\\.md$", "Templates/.*\\.md$"]

# Hinode theme module
[[module.imports]]
  path = "github.com/gethinode/hinode"

[params]
  description = "개발 및 인사이트 아카이빙 블로그"
  
  # Enable reading time and word count
  showReadingTime = true
  showWordCount = true
  showSummary = true
  showDate = true
  showAuthor = true
  
  # Hinode theme specific parameters
  [params.main]
    separator = " · "
    width = "fluid"
    color = "body"
  
  [params.style]
    themeColor = "#0d6efd"
    darkMode = true
    darkModeToggle = true
  
  [params.navigation]
    logo = "/images/logo-potato.svg"
    color = "body"
    fixed = true
    horizontal = false
    offset = "5.5rem"
    breadcrumb = true
    toc = true
    sidebar = false
    size = "md"
    [params.navigation.search]
      enabled = true
      modal = false
  
  [params.home]
    sections = ["blog"]
    fullCover = false
    centerHeadline = false
    style = ""
    lead = ""
    
  [params.sections]
    [params.sections.blog]
      title = "최근 글"
      sort = "date"
      reverse = true
      cols = 2
      homepage = 4
      padding = "4"
      header = "full"
      style = "card-zoom shadow"
      separator = true
      showDate = true
      showSummary = true
      showReadingTime = true
      showWordCount = true
  
  # Docs configuration (for content pages)
  [params.docs]
    showDate = true
    showAuthor = true
    showReadingTime = true
    showWordCount = true
    showSummary = true
    
  # Blog configuration
  [params.blog]
    showDate = true
    showAuthor = true
    showReadingTime = true
    showWordCount = true
    showSummary = true

# Languages
[languages]
  [languages.ko]
    languageName = "한국어"
    contentDir = "content"
    weight = 1

# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
